export default [
  {
    name: '通话时间',
    key: 'customer.callTime',
    searchbar_visible: false,
    header_visible: true,
    data_type: 'date',
    search_enabled: true,
    search_style: 'dateRange',
    search_type: 'range',
    sort_enable: true,
    sort_order: 1, 
  },
  {
    name: '最新跟进时间',
    key: 'customer.lastTime',
    searchbar_visible: false,
    header_visible: true,
    data_type: 'date',
    search_enabled: true,
    search_style: 'dateRange',
    search_type: 'range',
    sort_enable: true,
    sort_order: 1, 
  },
  {
    name: '手机号',
    key: 'customer.phone',
    searchbar_visible: false,
    header_visible: true,
    data_type: 'plaintext',
    search_enabled: true,
    search_style: 'search',
    search_type: 'search',
    sort_enable: true,
    sort_order: 1, 
  },
  {
    name: '客户详情',
    key: 'customer.customerUrl',
    searchbar_visible: false,
    header_visible: true,
    data_type: 'link',
    search_enabled: false,
    sort_enable: true,
    sort_order: 1, 
  },
  {
    name: '跟进人',
    key: 'customer.staff',
    searchbar_visible: false,
    header_visible: true,
    data_type: 'plaintext',
    search_enabled: true,
    sort_enable: true,
    sort_order: 1, 
  },
  {
    name: '姓名',
    key: 'customer.name',
    searchbar_visible: true,
    header_visible: true,
    data_type: 'plaintext',
    search_enabled: false,
    search_style: '',
    search_type: 'eq',
    sort_enable: false,
    sort_order: 0,
  },
  {
    name: '客户ID',
    key: 'customer.customerId',
    searchbar_visible: true,
    header_visible: true,
    data_type: 'plaintext',
    search_enabled: false,
    sort_enable: false,
    sort_order: 0,
  },
  {
    name: '通话时长',
    key: 'customer.talkTime',
    searchbar_visible: true,
    header_visible: false,
    data_type: 'plaintext',
    search_enabled: true,
    search_style: 'integerRange',
    search_type: 'range',
    sort_enable: true,
    sort_order: -1,
  },
  {
    name: '违规值',
    key: 'customer.violationValue',
    searchbar_visible: true,
    header_visible: true,
    data_type: 'plaintext',
    data_min_constraint: 0,
    data_max_constraint: 1,
    search_enabled: true,
    search_style: 'floatRange',
    search_type: 'range',
    sort_enable: true,
    sort_order: -1,
  },
  {
    name: '会话类型',
    key: 'customer.callType',
    searchbar_visible: false,
    header_visible: true,
    data_type: 'plaintext',
    search_enabled: true,
    search_style: 'radio',
    search_type: 'eq',
    sort_enable: true,
    sort_order: 1,
    search_items: {
      items: [
        {
          name: '全部',
          id: '-1',
        },
        {
          name: '录音',
          id: '1',
        },
        {
          name: '文本',
          id: '2',
        },
      ],
    },
  },
  {
    name: '质检结果',
    key: 'customer.qualityResult',
    searchbar_visible: true,
    header_visible: false,
    data_type: 'plaintext',
    search_enabled: true,
    search_style: 'radio',
    search_type: 'eq',
    sort_enable: true,
    sort_order: 1,
    search_items: {
      items: [
        {
          name: '全部',
          id: '-1',
        },
        {
          name: '合格',
          id: '1',
        },
        {
          name: '不合格',
          id: '2',
        },
      ],
    },
  },
];
